production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: Shana
  password: Lavina_18*

test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: Shana
  password: Lavina_18*